package org.taverna.server.master.scape.beanshells;

import static java.util.UUID.randomUUID;
import static javax.xml.bind.DatatypeConverter.printDateTime;
import static org.taverna.server.master.scape.beanshells.utils.XmlUtils.makeNewDocument;
import static org.taverna.server.master.scape.beanshells.utils.XmlUtils.parseDocument;
import static org.taverna.server.master.scape.beanshells.utils.XmlUtils.serializeDocument;
import info.lc.xmlns.premis_v2.EventComplexType;
import info.lc.xmlns.premis_v2.EventOutcomeDetailComplexType;
import info.lc.xmlns.premis_v2.EventOutcomeInformationComplexType;
import info.lc.xmlns.premis_v2.ExtensionComplexType;
import info.lc.xmlns.premis_v2.LinkingObjectIdentifierComplexType;
import info.lc.xmlns.premis_v2.ObjectFactory;
import info.lc.xmlns.premis_v2.PremisComplexType;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBException;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactoryConfigurationError;

import org.taverna.server.master.scape.beanshells.BeanshellSupport.Name;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

import eu.scape_project.model.File;
import eu.scape_project.model.File.Builder;
import eu.scape_project.model.Identifier;
import eu.scape_project.model.Representation;
import eu.scape_project.util.ScapeMarshaller;

@Name("ConstructNewRepresentationDocument")
public class ConstructNewMetadata extends Support<ConstructNewMetadata> {
	@Input
	private String originalMetadata;
	@Input
	private List<String> originalFileID;
	@Input
	private String representationId;
	@Input
	private List<String> newInformation;
	@Input(required = false)
	private List<String> generatedFileUri;
	@Input
	private String creator;
	@Input(required = false)
	private List<String> contentType;
	@Input(required = false)
	private List<String> isSatisfied;
	@Input
	private String planID;
	@Output
	private String newMetadata;
	@Output
	private String newRepresentationId;

	private final ScapeMarshaller sm;
	private final ObjectFactory factory;
	private final Document doc;

	public ConstructNewMetadata() throws JAXBException,
			ParserConfigurationException {
		sm = ScapeMarshaller.newInstance();
		factory = new ObjectFactory();
		doc = makeNewDocument();
	}

	private static <T> T next(Iterator<T> iterator) {
		return (iterator != null && iterator.hasNext()) ? iterator.next()
				: null;
	}

	private static <T> Iterator<T> iterate(Iterable<T> iterable) {
		return iterable != null ? iterable.iterator() : null;
	}

	@Override
	public void op() throws Exception {
		newRepresentationId = randomUUID().toString();

		Representation original = sm.deserialize(Representation.class,
				new ByteArrayInputStream(originalMetadata.getBytes()));

		Map<String, Integer> fileindexmap = new HashMap<>();
		int idx = 0;
		for (File f : original.getFiles())
			fileindexmap.put(f.getIdentifier().getValue(), idx++);

		Representation.Builder rep = new Representation.Builder(original)
				.identifier(new Identifier(newRepresentationId)).title(
						"representation generated by " + creator);
		StringBuilder overallFileInfo = new StringBuilder(
				"<planExecutionDetails plan=\"").append(planID).append("\">");
		if (generatedFileUri != null) {
			List<File> updatedFiles = new ArrayList<>(original.getFiles());
			Iterator<String> newMeta = iterate(newInformation);
			Iterator<String> origFile = iterate(originalFileID);
			Iterator<String> ct = iterate(contentType);
			Iterator<String> satisfied = iterate(isSatisfied);
			for (String fileUri : generatedFileUri)
				processOneFileEntry(next(satisfied), next(newMeta),
						next(origFile), fileindexmap, overallFileInfo,
						next(ct), updatedFiles, fileUri);
			rep.files(updatedFiles);
		}
		overallFileInfo.append("</planExecutionDetails>");
		rep.provenance(generatePremisEvent(representationId,
				overallFileInfo.toString()));

		ByteArrayOutputStream baos = new ByteArrayOutputStream();
		sm.serialize(rep.build(), baos);
		newMetadata = baos.toString();
	}

	private JAXBElement<?> generatePremisEvent(String contextID, String details) {
		Element p = doc.createElementNS("http://www.w3.org/1999.xhtml", "p");
		p.appendChild(doc.createCDATASection(details));

		EventComplexType ev = factory.createEventComplexType();
		ev.setEventType("migration");
		ev.setEventDateTime(printDateTime(Calendar.getInstance()));
		ev.setEventDetail("The plan " + planID
				+ " was applied to generate a new representation.");
		EventOutcomeInformationComplexType outcome = factory
				.createEventOutcomeInformationComplexType();
		ev.getEventOutcomeInformation().add(outcome);
		outcome.getContent().add(factory.createEventOutcome("success"));
		EventOutcomeDetailComplexType detail = factory
				.createEventOutcomeDetailComplexType();
		outcome.getContent().add(factory.createEventOutcomeDetail(detail));
		detail.setEventOutcomeDetailNote("detected properties");
		ExtensionComplexType ext = factory.createExtensionComplexType();
		detail.getEventOutcomeDetailExtension().add(ext);
		ext.getAny().add(p);

		LinkingObjectIdentifierComplexType loid = factory
				.createLinkingObjectIdentifierComplexType();
		loid.setLinkingObjectIdentifierType("RODAObjectPID");
		loid.setLinkingObjectIdentifierValue(contextID);
		loid.getLinkingObjectRole().add("target");
		ev.getLinkingObjectIdentifier().add(loid);

		PremisComplexType premis = factory.createPremisComplexType();
		premis.getEvent().add(ev);
		return factory.createPremis(premis);
	}

	private void processOneFileEntry(String satisfied, String newInformation,
			String originalFileID, Map<String, Integer> fileindexmap,
			StringBuilder overallFileInfo, String contentType,
			List<eu.scape_project.model.File> updatedFiles,
			String generatedFileUri) throws ParserConfigurationException,
			SAXException, IOException, TransformerFactoryConfigurationError,
			TransformerException {
		if (satisfied != null && !Boolean.parseBoolean(satisfied))
			return;
		String id = originalFileID.replaceFirst("^.*/", "");
		Integer idx = fileindexmap.get(id);
		if (idx == null)
			id = randomUUID().toString();
		Element m = parseDocument(newInformation).getDocumentElement();

		Element fileInfo = doc.createElement("file");
		fileInfo.setAttribute("id", id);
		NodeList nl = m.getElementsByTagNameNS(
				"http://ns.taverna.org.uk/2014/scape", "measure");
		for (int i = 0; i < nl.getLength(); i++) {
			Element measure = (Element) nl.item(i);
			Element qa = doc.createElement("qa");
			qa.setAttribute("property", measure.getAttribute("type"));
			qa.setTextContent(measure.getTextContent());
			fileInfo.appendChild(qa);
		}
		overallFileInfo.append(serializeDocument(fileInfo));

		Builder file = new Builder().identifier(new Identifier(id))
				.uri(URI.create(generatedFileUri))
				// .filename(fileHandle.getName())
				.technical(m);
		if (contentType != null)
			file.mimetype(contentType);
		if (idx == null)
			updatedFiles.add(file.build());
		else
			updatedFiles.set(idx, file.build());
	}
}
